//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataNotas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompraNotasCatalogos
    {
        public int id { get; set; }
        public int idNotas { get; set; }
        public int idCatalogos { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
    
        public virtual Catalogos Catalogos { get; set; }
        public virtual Notas Notas { get; set; }

        public decimal precioFinal 
        {
            get
            {
                return Cantidad * PrecioUnitario;
            }
        }
    }
}
